"""New Migration

Revision ID: 194bd6dfaab0
Revises: 5109224289a8
Create Date: 2023-06-27 15:48:56.771603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194bd6dfaab0'
down_revision = '5109224289a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_binary_results_sequence_id', table_name='binary_results')
    op.create_index('sequence_id_index', 'binary_results', ['sequence_id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sequence_id_index', table_name='binary_results', postgresql_using='hash')
    op.create_index('ix_binary_results_sequence_id', 'binary_results', ['sequence_id'], unique=False)
    # ### end Alembic commands ###
