"""New Migration

Revision ID: 2e3e4b33b884
Revises: 74581b66ed98
Create Date: 2023-07-18 16:42:14.223632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3e4b33b884'
down_revision = '74581b66ed98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sequence_id_index', 'binary_results', ['sequence_id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sequence_id_index', table_name='binary_results', postgresql_using='hash')
    # ### end Alembic commands ###
