"""New Migration

Revision ID: 4bf1fc38fcf0
Revises: 2e3e4b33b884
Create Date: 2023-08-01 13:52:33.973756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf1fc38fcf0'
down_revision = '2e3e4b33b884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_name_and_uuid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_name_and_uuid_id'), 'file_name_and_uuid', ['id'], unique=False)
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.String(), nullable=True),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.Column('sequence_length', sa.Integer(), nullable=True),
    sa.Column('min_quality', sa.Integer(), nullable=True),
    sa.Column('max_quality', sa.Integer(), nullable=True),
    sa.Column('average_quality', sa.Float(), nullable=True),
    sa.Column('phred_quality', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_name_and_uuid.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id')
    )
    op.create_index(op.f('ix_raw_data_id'), 'raw_data', ['id'], unique=False)
    op.create_table('binary_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_name_and_uuid.id'], ),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binary_results_id'), 'binary_results', ['id'], unique=False)
    op.create_index('sequence_id_index', 'binary_results', ['sequence_id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sequence_id_index', table_name='binary_results', postgresql_using='hash')
    op.drop_index(op.f('ix_binary_results_id'), table_name='binary_results')
    op.drop_table('binary_results')
    op.drop_index(op.f('ix_raw_data_id'), table_name='raw_data')
    op.drop_table('raw_data')
    op.drop_index(op.f('ix_file_name_and_uuid_id'), table_name='file_name_and_uuid')
    op.drop_table('file_name_and_uuid')
    # ### end Alembic commands ###
