"""New Migration

Revision ID: 5109224289a8
Revises: 
Create Date: 2023-06-27 15:15:00.614361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5109224289a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_name_and_uuid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('binary_of_origin', sa.String(), nullable=True),
    sa.Column('file_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_name_and_uuid_id'), 'file_name_and_uuid', ['id'], unique=False)
    op.create_table('binary_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_name_and_uuid.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binary_results_id'), 'binary_results', ['id'], unique=False)
    op.create_index(op.f('ix_binary_results_sequence_id'), 'binary_results', ['sequence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binary_results_sequence_id'), table_name='binary_results')
    op.drop_index(op.f('ix_binary_results_id'), table_name='binary_results')
    op.drop_table('binary_results')
    op.drop_index(op.f('ix_file_name_and_uuid_id'), table_name='file_name_and_uuid')
    op.drop_table('file_name_and_uuid')
    # ### end Alembic commands ###
