"""New Migration

Revision ID: 6fd59d72b1ed
Revises: 13c17cd1a979
Create Date: 2023-07-05 17:58:33.460210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd59d72b1ed'
down_revision = '13c17cd1a979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
