"""New Migration

Revision ID: 74581b66ed98
Revises: c0ec45b93bec
Create Date: 2023-07-06 15:58:32.784932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74581b66ed98'
down_revision = 'c0ec45b93bec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
