"""New Migration

Revision ID: a7d8d2671546
Revises: 79bad9d1a2f4
Create Date: 2023-07-03 13:07:43.442401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d8d2671546'
down_revision = '79bad9d1a2f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
