"""New Migration

Revision ID: c0ec45b93bec
Revises: 6fd59d72b1ed
Create Date: 2023-07-06 15:54:05.990927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ec45b93bec'
down_revision = '6fd59d72b1ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
